"""Auto-split from agent_runtime.py — see docs for module boundaries."""

from __future__ import annotations

import hashlib
import os
import re

from pathlib import Path
from datetime import datetime, timezone
from typing import Any

from hooky.runtime.models import runtime_path
from hooky.runtime.rendering import utc_timestamp


def read_tail(path: Path, max_bytes: int) -> str:
    if not path.exists():
        return ""
    max_bytes = max(1, max_bytes)
    with path.open("rb") as handle:
        handle.seek(0, os.SEEK_END)
        size = handle.tell()
        handle.seek(max(size - max_bytes, 0))
        return handle.read(max_bytes).decode("utf-8", errors="replace")


def read_text_prefix(path: Path, max_bytes: int) -> str:
    with path.open("rb") as handle:
        return handle.read(max(1, max_bytes)).decode("utf-8", errors="replace")


def content_sha256(content: str) -> str:
    return hashlib.sha256(content.encode("utf-8")).hexdigest()


def file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def write_tool_result_artifact(root: Path, category: str, content: str) -> str:
    directory = runtime_path(root, "tool-results", category)
    directory.mkdir(parents=True, exist_ok=True)
    filename = utc_timestamp().replace(":", "").replace("+", "Z") + ".log"
    path = directory / filename
    path.write_text(content, encoding="utf-8")
    return relative_to(path, root)


def evidence_assets_dir(evidence_base_dir: Path, category: str) -> Path:
    path = evidence_base_dir / "evidence" / category
    path.mkdir(parents=True, exist_ok=True)
    return path


def evidence_stamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ%f")[:22]


def ensure_evidence_report(root: Path, evidence_base_dir: Path) -> Path:
    path = evidence_base_dir / "evidence.md"
    if not path.exists():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            "# Evidence\n\n"
            "Generated by Hooky evidence tools. Command output and screenshots in this report are captured by tools, not hand-authored by the model.\n\n",
            encoding="utf-8",
        )
    return path


def append_evidence_section(root: Path, evidence_base_dir: Path, title: str, body: str) -> Path:
    path = ensure_evidence_report(root, evidence_base_dir)
    with path.open("a", encoding="utf-8") as handle:
        handle.write(f"## {title}\n\n")
        handle.write(f"- captured_at: {utc_timestamp()}\n\n")
        if body.strip():
            handle.write(body.rstrip() + "\n\n")
    return path


def fenced(value: str, language: str = "") -> str:
    fence = "```"
    while fence in value:
        fence += "`"
    info = language.strip()
    return f"{fence}{info}\n{value.rstrip()}\n{fence}"


def append_evidence_note_file(root: Path, evidence_base_dir: Path, *, title: str, body: str) -> Path:
    return append_evidence_section(root, evidence_base_dir, title, body)


def write_evidence_command_output(root: Path, evidence_base_dir: Path, *, command: str, output: str) -> Path:
    directory = evidence_assets_dir(evidence_base_dir, "command-output")
    slug = re.sub(r"[^A-Za-z0-9_.-]+", "-", command.strip()).strip(".-").lower()[:48] or "command"
    path = directory / f"{evidence_stamp()}-{slug}.log"
    path.write_text(output, encoding="utf-8")
    return path


def append_evidence_command_file(
    root: Path,
    evidence_base_dir: Path,
    *,
    title: str,
    command: str,
    returncode: int,
    timed_out: bool,
    started_at: str,
    ended_at: str,
    output_path: Path,
    output_tail: str,
    protected_changes: list[str],
) -> Path:
    lines = [
        f"- command: `{command}`",
        f"- returncode: {returncode}",
        f"- timed_out: {str(timed_out).lower()}",
        f"- started_at: {started_at}",
        f"- ended_at: {ended_at}",
        f"- output: `{relative_to(output_path, root)}`",
    ]
    if protected_changes:
        lines.append("- protected_changes_reverted: " + ", ".join(protected_changes[:20]))
    if output_tail.strip():
        lines.extend(["", fenced(output_tail[-4000:], "text")])
    return append_evidence_section(root, evidence_base_dir, title, "\n".join(lines))


def append_evidence_screenshot_file(root: Path, evidence_base_dir: Path, *, title: str, url: str, snapshot: dict[str, Any]) -> Path:
    screenshot = str(snapshot.get("screenshot_path") or "")
    lines = [
        f"- url: `{url}`",
        f"- ok: {str(bool(snapshot.get('ok'))).lower()}",
    ]
    if screenshot:
        lines.append(f"- screenshot: `{screenshot}`")
        lines.extend(["", f"![{title}]({screenshot})"])
    if snapshot.get("error"):
        lines.append(f"- error: {snapshot.get('error')}")
    metrics = snapshot.get("metrics") if isinstance(snapshot.get("metrics"), dict) else {}
    if metrics:
        lines.extend(
            [
                "",
                "- metrics:",
                f"  - viewportCoverage: {metrics.get('viewportCoverage')}",
                f"  - topGapRatio: {metrics.get('topGapRatio')}",
                f"  - leftGapRatio: {metrics.get('leftGapRatio')}",
                f"  - visibleElementCount: {metrics.get('visibleElementCount')}",
                f"  - headingInteractiveOverlapCount: {metrics.get('headingInteractiveOverlapCount')}",
            ]
        )
    return append_evidence_section(root, evidence_base_dir, title, "\n".join(lines))


def relative_to(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()



def visual_snapshot_script() -> str:
    return r"""
const fs = require('fs');

async function loadPlaywright() {
  try {
    return require('playwright');
  } catch (firstError) {
    try {
      return require('@playwright/test');
    } catch (_secondError) {
      throw firstError;
    }
  }
}

(async () => {
  const [url, screenshotPath, widthRaw, heightRaw, waitSelector, fullPageRaw] = process.argv.slice(2);
  const width = Number(widthRaw || 1280);
  const height = Number(heightRaw || 900);
  const fullPage = fullPageRaw === '1';
  const consoleMessages = [];
  const { chromium } = await loadPlaywright();
  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({ viewport: { width, height } });
  page.on('console', message => {
    if (['error', 'warning'].includes(message.type())) {
      consoleMessages.push({ type: message.type(), text: message.text().slice(0, 500) });
    }
  });
  page.on('pageerror', error => {
    consoleMessages.push({ type: 'pageerror', text: String(error.message || error).slice(0, 500) });
  });
  await page.goto(url, { waitUntil: 'networkidle', timeout: 30000 });
  if (waitSelector) {
    await page.waitForSelector(waitSelector, { timeout: 10000 });
  }
  const metrics = await page.evaluate(() => {
    const viewport = { width: window.innerWidth, height: window.innerHeight };
    const doc = document.documentElement;
    const body = document.body;
    const visibleElements = [];
    const interactiveElements = [];
    const textBlocks = [];
    const selectors = 'a,button,input,textarea,select,[role="button"],[role="link"],[tabindex]';
    function isVisible(element, rect, style) {
      return rect.width > 0 && rect.height > 0 &&
        style.visibility !== 'hidden' &&
        style.display !== 'none' &&
        Number(style.opacity || '1') > 0;
    }
    function asRect(rect) {
      return {
        x: Math.round(rect.x),
        y: Math.round(rect.y),
        width: Math.round(rect.width),
        height: Math.round(rect.height),
        right: Math.round(rect.right),
        bottom: Math.round(rect.bottom),
      };
    }
    for (const element of Array.from(document.body.querySelectorAll('*'))) {
      const rect = element.getBoundingClientRect();
      const style = window.getComputedStyle(element);
      if (!isVisible(element, rect, style)) continue;
      const tag = element.tagName.toLowerCase();
      const item = {
        tag,
        id: element.id || '',
        className: typeof element.className === 'string' ? element.className.slice(0, 120) : '',
        role: element.getAttribute('role') || '',
        text: (element.innerText || element.getAttribute('aria-label') || element.getAttribute('placeholder') || '').replace(/\s+/g, ' ').trim().slice(0, 160),
        rect: asRect(rect),
      };
      visibleElements.push(item);
      if (element.matches(selectors)) interactiveElements.push(item);
      if (item.text && rect.width > 10 && rect.height > 10) textBlocks.push(item);
    }
    const rects = visibleElements.map(item => item.rect).filter(rect => rect.width > 0 && rect.height > 0);
    const clippedElements = visibleElements.filter(item =>
      item.rect.x < 0 ||
      item.rect.y < 0 ||
      item.rect.right > viewport.width ||
      item.rect.bottom > viewport.height
    );
    const intersectionArea = rects.reduce((total, rect) => {
      const width = Math.max(0, Math.min(rect.right, viewport.width) - Math.max(rect.x, 0));
      const height = Math.max(0, Math.min(rect.bottom, viewport.height) - Math.max(rect.y, 0));
      return total + width * height;
    }, 0);
    let bounds = null;
    if (rects.length) {
      bounds = {
        x: Math.min(...rects.map(rect => rect.x)),
        y: Math.min(...rects.map(rect => rect.y)),
        right: Math.max(...rects.map(rect => rect.right)),
        bottom: Math.max(...rects.map(rect => rect.bottom)),
      };
      bounds.width = bounds.right - bounds.x;
      bounds.height = bounds.bottom - bounds.y;
    }
    const viewportArea = viewport.width * viewport.height;
    const boundsArea = bounds ? Math.max(bounds.width, 0) * Math.max(bounds.height, 0) : 0;
    const center = bounds ? {
      x: Math.round(bounds.x + bounds.width / 2),
      y: Math.round(bounds.y + bounds.height / 2),
      offsetX: Math.round(bounds.x + bounds.width / 2 - viewport.width / 2),
      offsetY: Math.round(bounds.y + bounds.height / 2 - viewport.height / 2),
    } : null;
    const headings = Array.from(document.querySelectorAll('h1,h2,h3,[role="heading"]')).map(element => ({
      text: (element.innerText || '').replace(/\s+/g, ' ').trim().slice(0, 160),
      tag: element.tagName.toLowerCase(),
      role: element.getAttribute('role') || '',
      rect: asRect(element.getBoundingClientRect()),
    }));
    function intersectionRatio(a, b) {
      const width = Math.max(0, Math.min(a.right, b.right) - Math.max(a.x, b.x));
      const height = Math.max(0, Math.min(a.bottom, b.bottom) - Math.max(a.y, b.y));
      const area = width * height;
      const smallest = Math.max(1, Math.min(a.width * a.height, b.width * b.height));
      return Number((area / smallest).toFixed(4));
    }
    const headingInteractiveOverlaps = [];
    for (const heading of headings) {
      for (const interactive of interactiveElements) {
        const ratio = intersectionRatio(heading.rect, interactive.rect);
        if (ratio > 0.01) {
          headingInteractiveOverlaps.push({
            headingText: heading.text,
            headingTag: heading.tag,
            headingRect: heading.rect,
            interactiveText: interactive.text,
            interactiveTag: interactive.tag,
            interactiveRole: interactive.role,
            interactiveClassName: interactive.className,
            interactiveRect: interactive.rect,
            overlapRatio: ratio,
          });
        }
      }
    }
    return {
      title: document.title,
      location: window.location.href,
      viewport,
      document: {
        scrollWidth: doc.scrollWidth,
        scrollHeight: doc.scrollHeight,
        bodyTextLength: (body.innerText || '').length,
      },
      contentBounds: bounds,
      contentCenter: center,
      viewportCoverage: Number((boundsArea / viewportArea).toFixed(4)),
      visiblePaintCoverage: Number((intersectionArea / viewportArea).toFixed(4)),
      topGapRatio: bounds ? Number((Math.max(bounds.y, 0) / viewport.height).toFixed(4)) : 1,
      leftGapRatio: bounds ? Number((Math.max(bounds.x, 0) / viewport.width).toFixed(4)) : 1,
      horizontalOverflow: doc.scrollWidth > viewport.width + 2,
      verticalOverflow: doc.scrollHeight > viewport.height + 2,
      clippedElementCount: clippedElements.length,
      headingInteractiveOverlapCount: headingInteractiveOverlaps.length,
      visibleElementCount: visibleElements.length,
      interactiveElementCount: interactiveElements.length,
      headings: headings.slice(0, 12),
      sampleHeadingInteractiveOverlaps: headingInteractiveOverlaps.slice(0, 20),
      sampleClippedElements: clippedElements.slice(0, 20),
      sampleVisibleElements: visibleElements.slice(0, 40),
      sampleInteractiveElements: interactiveElements.slice(0, 30),
      sampleTextBlocks: textBlocks.slice(0, 30),
    };
  });
  await page.screenshot({ path: screenshotPath, fullPage });
  await browser.close();
  console.log(JSON.stringify({
    url,
    screenshotBytes: fs.statSync(screenshotPath).size,
    consoleMessages,
    metrics,
  }));
})().catch(error => {
  console.error(error && error.stack ? error.stack : String(error));
  process.exit(1);
});
"""


